'use strict';
const test = require('node:test'); const assert = require('node:assert/strict');
const { EventBus } = require('../src/event-bus'); const { ActivityTracker } = require('../src/activity-tracker'); const { resolve } = require('../src/template-resolver'); const { clamp } = require('../src/shared');
const { CommandParser } = require('../src/command-parser'); const { ReactionScheduler } = require('../src/reaction-scheduler');
test('activity tracker derives rolling switch counts from actual event timestamps', () => { const bus = new EventBus(); const tracker = new ActivityTracker(bus); let changes = 0; bus.on('APP_CHANGED', () => changes++); [0, 10, 20, 30].forEach((at, i) => tracker.ingest({ type: 'APP_CHANGED', source: 'macos', timestamp: 1_000 + at, app: { name: `App ${i}`, bundleId: `test.${i}` } })); assert.equal(tracker.snapshot(1_040).switchesLast1m, 4); assert.equal(changes, 4); assert.equal(tracker.snapshot(2_040).history[0].durationMs, 10); });
test('template resolver rejects unknown variables and resolves known ones', () => { assert.deepEqual(resolve('Hi {{banana.time}}', { app: {} }), { ok: false, text: '', unknown: ['banana.time'] }); assert.deepEqual(resolve('Switched {{app.switchCount5m}} times', { app: { switchCount5m: 5 } }), { ok: true, text: 'Switched 5 times', unknown: [] }); });
test('state values are clamped inclusively', () => { assert.equal(clamp(-2), 0); assert.equal(clamp(101), 100); assert.equal(clamp(42.5), 43); });
test('Gemini parsing applies only the first valid command when priority mode is enabled', () => { const changes = []; const parser = new CommandParser({ state: { set: (key, value) => changes.push([key, value]) }, bus: new EventBus(), reactions: { save: () => ({ ok: true }), templateContext: () => ({}) } }); const result = parser.parse('CHANGELOVE: 91\nEMOTE: angry\nHi.', { firstCommandOnly: true }); assert.deepEqual(changes, [['love', 91]]); assert.deepEqual(result.commands, ['CHANGELOVE']); assert.equal(result.text, 'Hi.'); });
test('ignored nudges escalate only after a randomized threshold', () => { const scheduler = new ReactionScheduler({ snapshot: () => ({ annoyance: 30 }) }); scheduler.ignoredNudgesUntil = 2; assert.equal(scheduler.recordIgnoredNudge(), false); assert.equal(scheduler.recordIgnoredNudge(), true); });
